FROM harbor.qifand.com/llm-infer/vllm-openai-base:latest AS builder

RUN apt update && apt install -y unzip
RUN wget https://github.com/pancak3/LMCache/archive/refs/heads/dev.zip
RUN unzip dev.zip && cd LMCache-dev && cp -r lmcache/* /usr/local/lib/python3.12/dist-packages/lmcache/

COPY vllm.tar /tmp/vllm.tar
RUN mkdir -p /tmp/project && cd /tmp/project && tar -xf /tmp/vllm.tar && \
	cp -r /tmp/project/vllm/entrypoints/* /usr/local/lib/python3.12/dist-packages/vllm/entrypoints/


FROM harbor.qifand.com/llm-infer/vllm-openai-base:latest

COPY --from=builder /usr/local/lib/python3.12/dist-packages/ /usr/local/lib/python3.12/dist-packages/

COPY ./docker/run.sh /usr/local/bin/run.sh
ENTRYPOINT ["/usr/local/bin/run.sh"]